# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Honest Abe Blog
email: kwhittin@uno.edu
description: > # this means to ignore newlines until "baseurl:"
  The blog for the Spring 2016 UNO CSCI 4675 class project, Honest Abe.
baseurl: "/honest_abe_blog"
url: "http://uno-csci-4675.github.io"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
